### ISSUE TITLE
Encode/Decode error for nonode@nohost PIDs

### ISSUE THREAD

**Issue by point** [appulse-projects/encon-java#10] opened 2018-09-27 16:13 UTC
It seems encon doesn't survive while decoding->encoding+serializing PIDs in format of `#PID<0.639.0>`

Exception: 
```
io.appulse.encon.terms.exception.IllegalErlangTermTypeException: Class io.appulse.encon.ter
ms.type.ErlangAtom doesn't fit to term type ATOM
```

Steps to reproduce:
1. In Elixir: File.write!("pid.term", :erlang.term_to_binary(self))
2. On Java side: 
  Read the first byte of "pid.term" file (it's 131)
3. Read the rest into ByteBuf
4. Decode bytebuf into proper java class with ErlangTerm/newInstance
5. Encode/serialize it to another ByteBuf. Get the error above.

I suspect that the atom for node name of such PID constructs with incorrect value field:
```
#object[io.appulse.encon.terms.type.ErlangAtom 0x1c433450 "ErlangAtom(value=nu
ll, bytes=[110, 111, 110, 111, 100, 101, 64, 110, 111, 104, 111, 115, 116], ch
arset=ISO-8859-1)"]
```

**Comment by xxlabaza** [comment] 2018-09-27 16:18
@point thanks for your issue, it will be fixed ASAP.

**Comment by xxlabaza** [comment] 2018-09-28 07:33
k, I have fixed it. 

The new version is available at the **master** branch and now, Travis, builds release **1.6.5** with that quick fix, after a few hours it will be available at Maven Central, and you can use it in your project.

The cause of the exception was - missing `ATOM` and `SMALL_ATOM` serialization cases, you can see it [here](https://github.com/appulse-projects/encon-java/commit/8c4b070bd12bb88efe98dc1b8c56d29562f653be#diff-2c7a69ce64cfce2e3799d22089f25f0cL222).

Thanks again for the time which you spent on writing the issue and I hope you will enjoy working with my lib =)

**Closed as completed by xxlabaza** 2018-09-28 07:33 UTC
Labels: bug

**Comment by point** [comment] 2018-09-28 15:45
Caught up 1.6.5 from maven central. Now everything works great!
Thanks a lot!
